### ISSUE TITLE
Is bash completion planned or will original lunchy completion work?

### ISSUE THREAD

**Issue by fgimian** [sosedoff/lunchy-go#5]
Hello there, great job with your port of lunchy :smile: 

What's the current status of bash completion?  Will the original bash completion from lunchy work?

Cheers
Fotis

**Comment by sosedoff** [comment]
Hi. It might work, but i never tested it. Im not planning on any bash completion work. If you feel that it could be helpful - go ahead and submit PR if you're interested.
