### ISSUE TITLE
Lunchy 0.2.0 fails to parse LaunchAgents

### ISSUE THREAD

**Issue by vendion** [sosedoff/lunchy-go#6]
Using `lunchy` 0.2.0 compiled with Go 1.5.1 running the following commands fail:

```
~> lunchy ls
.
~> lunchy scan ~/Library/LaunchAgents
.
~> lunchy status
~> lunchy restart php55
~>
```

I know that I do infact have launch agents installed on my system as `ls ~/Library/LaunchAgents` returns

```
com.Aether.Aether.plist
com.google.Chrome.framework.plist
homebrew.mxcl.mariadb.plist@
homebrew.mxcl.mpd.plist@
homebrew.mxcl.nginx-full.plist@
homebrew.mxcl.php55.plist@
homebrew.mxcl.postgresql.plist@
homebrew.mxcl.solr36.plist@
me.vendion.devdns.plist
net.tunnelblick.tunnelblick.LaunchAtLogin.plist
org.virtualbox.vboxwebsrv.plist
```

**Comment by sosedoff** [comment]
Thanks for the bug report. Do you see the same issue using go1.4.2 ?

**Comment by vendion** [comment]
No lunchy seemed to be working fine under go 1.4.x, but I was also using a 1.x version of lunchy at the time (can't remember which one it was exactly).  So I'm not sure if it was the Go 1.5 bump or Lunchy 0.2.0 bump that broke things, or maybe both.  I can try to take a better look at it after work, see if I can't pin it down to something more specific.

**Comment by sosedoff** [comment]
Yeah, i'll need to add some tests so CI can verify all features. Try using a binary release and see if that works.

**Comment by vendion** [comment]
The problem seems to be with the find command on [line 44](https://github.com/sosedoff/lunchy-go/blob/master/lunchy.go#L44).  First it is looking for files that start with `homebrew` which in my case is only a subset of my plists.  Second wildcards in the find command needs escaped with a backslash `\`.  Third the find command on OSX seems to ignore symlinks when `-type f` is used, which all of my homebrew plists are symlinks pointing to the plist from `/usr/local` that homebrew installs.  To work around this either the `-type` flag should be dropped or the `-L` flag added.

So if I change line 44 in lunchy.go to either one of the following everything works with Lunchy 0.2.0 with Go 1.5

```go
output, err := exec.Command("find", "-L", path, "-name", `\*.plist`, "-type", "f").Output()
```

```go
output, err := exec.Command("find", path, "-name", `\*.plist`, "-print").Output()
```

They both work the same way and handles files and symlinks alike.

As a bonus here is a pure Go version that doesn't rely on external system calls https://gist.github.com/vendion/ce97e6c9bb0a94ac29f6

**Comment by sosedoff** [comment]
Oh regarding line 44, indeed its a bug. If you look at previous lunchy version that does not use `find` it works correctly, which is also similar to the code you've provided. It was supposed to be doing `*.plist` and not `homebrew.*.plist` and this is something that (again) i should have fixed by adding tests :(

**Comment by sosedoff** [comment]
This should be fixed in latest release.
