### ISSUE TITLE
Homebrew Cask vs Homebrew

### ISSUE THREAD

**Issue by jmmk** [sosedoff/lunchy-go#8]
Why is this included as a Cask instead of as a normal Formula? I thought Casks were more for GUI apps and that cli apps were normally included in the standard repository.

Not a big deal to type an extra word to install, but just curious.

**Comment by sosedoff** [comment]
Homebrew-based formulas are supposed to be built from the source code. Which does not make sense to use for this project since it would require Go compiler to be installed first.

**Comment by jmmk** [comment]
As an example, [Docker](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker.rb) is in the Homebrew repository. It has a dependency on go if you need to build it from source, but by default it will be installed from the pre-compiled "Bottle" found [here](https://bintray.com/homebrew/bottles/docker/1.9.1/view#files).

**Comment by sosedoff** [comment]
Thats cool, i dont really care if its a cask or a regular formula as long as it works and could be easily installed. In fact someone else created the original lunchy formula - https://github.com/caskroom/homebrew-cask/commit/5a8ec4131f8b533abf471d3846e12adf59889749 - i've been just updating it.

**Comment by jmmk** [comment]
Yep, I don't see a compelling reason to make the switch since it works just fine as-is. Thanks!
